import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#39342d",
        "surface-container-highest": "#39342d",
        "on-surface": "#ebe1d6",
        "primary-fixed": "#ffdeaa",
        "on-tertiary": "#00315d",
        "tertiary-fixed-dim": "#a4c9ff",
        "surface-container-low": "#1f1b14",
        "surface-container-high": "#2e2922",
        "tertiary-container": "#94bffc",
        "on-secondary-container": "#ff9f93",
        "on-tertiary-container": "#1b4d83",
        "on-primary-fixed-variant": "#5f4100",
        "on-tertiary-fixed": "#001c39",
        surface: "#17130d",
        "surface-container": "#231f18",
        "surface-tint": "#f3be60",
        "on-primary": "#422c00",
        "secondary-fixed": "#ffdad5",
        tertiary: "#c3daff",
        "on-secondary-fixed-variant": "#891d18",
        background: "#17130d",
        primary: "#ffd185",
        error: "#ffb4ab",
        "inverse-primary": "#7d5700",
        "on-error": "#690005",
        "secondary-container": "#8c1f1a",
        "inverse-on-surface": "#353028",
        "on-surface-variant": "#d3c4b1",
        "inverse-surface": "#ebe1d6",
        "error-container": "#93000a",
        "on-primary-fixed": "#271900",
        "secondary-fixed-dim": "#ffb4aa",
        "on-error-container": "#ffdad6",
        secondary: "#ffb4aa",
        "surface-bright": "#3e3831",
        "outline-variant": "#4f4537",
        "surface-dim": "#17130d",
        "on-secondary": "#680105",
        "surface-container-lowest": "#110e08",
        "on-tertiary-fixed-variant": "#13487d",
        "primary-container": "#e8b457",
        "on-primary-container": "#654600",
        outline: "#9b8f7d",
        "primary-fixed-dim": "#f3be60",
        "on-background": "#ebe1d6",
        "tertiary-fixed": "#d4e3ff",
        "on-secondary-fixed": "#410002",
        canvas: "#0E0E11",
        elevated: "#1C1C22",
        hairline: "#2A2A33",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        gutter: "24px",
        unit: "4px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
      },
      fontFamily: {
        "display-lg": ["var(--font-sora)", "sans-serif"],
        "display-md": ["var(--font-sora)", "sans-serif"],
        "headline-lg": ["var(--font-sora)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-sora)", "sans-serif"],
        "title-md": ["var(--font-dm-sans)", "sans-serif"],
        "body-lg": ["var(--font-dm-sans)", "sans-serif"],
        "body-sm": ["var(--font-dm-sans)", "sans-serif"],
        "label-caps": ["var(--font-dm-sans)", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "0.02em", fontWeight: "700" }],
        "display-md": ["36px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "1.3", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", letterSpacing: "0.01em", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "1.5", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
